import {makeStyles} from '@material-ui/core/styles';
const useStyles=makeStyles(theme=>({
    root:{
        width:'400px',
        height:'600px',
        boxSizing:'border-box',
        position:'relative',
        borderRadius:'10px',
        justifyContent:'center',
        overflow:'hidden',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        border:`3px solid ${theme.palette.secondary.main}`,
        background:'#FFF'
    },
    name_typo:{
        color:'#FFF',
        fontFamily:"'Noto Sans KR', sans-serif",
        zIndex:100,
        position:'absolute',
        bottom:'10px',
        left:'10px'
    },
    img:{
        width:'100%',
        height:'100%',
        position:'absolute',
    },
    title_wrapper:{
        position:'absolute',
        top:'0px',
        left:'0px',
        background:'rgb(0,0,0,0.8)',
        width:'100%',
        height:'100%',
        display:'flex',
        flexFlow:'column nowrap',
        justifyContent:'center',
        alignItems:'center'
    },
    typo_common:{
        fontFamily:"'Noto Sans KR', sans-serif",
        textAlign:'center',
        background:'none',
        color:'#FFF',
        border:'none',
        '&:focus':{
            outline:'none'
        },
        '&::placeholder':{
            color:'#a6a6a6'
        }
    },
    typo_1:{
        width:'95%',
        fontSize:'20px',
    },
    typo_2:{
        resize:'none',
        width:'250px',
        height:'150px',
        fontSize:'12px',
        fontWeight:'light'
    },
    typo_3:{
        width:'250px',
        fontSize:'12px',
        fontWeight:'light'
    },
    separator:{
        content:'',
        width:'200px',
        borderBottom:'1.5px solid #FFF',
        marginTop:'15px',
        marginBottom:'15px'
    },
    textFiled_common:{
        fontFamily:"'Noto Sans KR', sans-serif",
        textAlign:'center',
        background:'none',
        color:'#FFF',
        border:'none',
        '&:focus':{
            outline:'none'
        },
        '&::placeholder':{
            color:'#a6a6a6'
        }
    },
    textFiled_1:{
        width:'95%',
        fontSize:'20px',
    },
    textFiled_2:{
        resize:'none',
        width:'250px',
        height:'150px',
        fontSize:'12px',
        fontWeight:'light'
    },
    textFiled_3:{
        width:'250px',
        fontSize:'12px',
        fontWeight:'light'
    },
    length_typo:{
        color:'#a6a6a6',
        fontSize:'8px'
    }
}))
export default useStyles;